apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.name }}
  annotations:
    cert-manager.io/cluster-issuer: {{ .Values.issuer }}
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/enable-cors: "false"
spec:
  tls:
  - hosts:
    - {{ .Values.host }}
    secretName: {{ .Values.tlsSecretName }}
  rules:
  - host: {{ .Values.host }}
    http:
      paths:
      - path: /(.*)
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.name }}
            port:
              number: {{ .Values.portService }}
