image: "ghcr.io/catenax-ng/product-portal-hello-helm:main"
portContainer: 8080
portService: 8080
replicaCount: 1
name: "hello-helm"
host: "hello-helm.demo.catena-x.net"
issuer: "letsencrypt-prod"
tlsSecretName: "tls-secret"